---
# Source: comfyui/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comfyui
  namespace: comfyui
  labels:
    app.kubernetes.io/name: comfyui
    app.kubernetes.io/instance: comfyui
automountServiceAccountToken: true
